import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { QuotationPdfData } from "./types";

const CATEGORY_LABEL: Record<QuotationPdfData["lineItems"][number]["category"], string> = {
  FREIGHT: "Freight Charges",
  CUSTOMS_CLEARANCE: "Customs Clearance Charges",
  TRANSPORTATION: "Transportation Charges",
  REIMBURSEMENT: "Reimbursement Charges",
};

const CATEGORY_ORDER = ["FREIGHT", "CUSTOMS_CLEARANCE", "TRANSPORTATION", "REIMBURSEMENT"] as const;

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica", color: "#2B2A26" },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 4, color: "#2FA8B5" },
  subtitle: { fontSize: 10, color: "#8A8578", marginBottom: 16 },
  headerGrid: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  headerCol: { flexDirection: "column", gap: 2 },
  label: { fontSize: 8, color: "#8A8578", textTransform: "uppercase" },
  value: { fontSize: 10, marginBottom: 6 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginTop: 14,
    marginBottom: 4,
    paddingBottom: 2,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E1D8",
  },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
  rowDescription: { flex: 1 },
  rowAmount: { width: 100, textAlign: "right" },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 14,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#2B2A26",
    fontSize: 12,
    fontWeight: 700,
  },
  enquiryList: { marginTop: 4 },
  footer: { marginTop: 24, fontSize: 8, color: "#8A8578" },
});

export function QuotationDocument({ data }: { data: QuotationPdfData }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Quotation {data.ref}</Text>
        <Text style={styles.subtitle}>
          Version {data.versionNumber} · {data.status.replace(/_/g, " ")}
          {data.approvedAt ? ` · Approved ${new Date(data.approvedAt).toLocaleDateString()}` : ""}
        </Text>

        <View style={styles.headerGrid}>
          <View style={styles.headerCol}>
            <Text style={styles.label}>Customer</Text>
            <Text style={styles.value}>{data.organizationName}</Text>
            <Text style={styles.label}>Branch</Text>
            <Text style={styles.value}>{data.branchName}</Text>
          </View>
          <View style={styles.headerCol}>
            <Text style={styles.label}>Prepared By</Text>
            <Text style={styles.value}>{data.createdByName}</Text>
            <Text style={styles.label}>Date</Text>
            <Text style={styles.value}>{new Date(data.createdAt).toLocaleDateString()}</Text>
          </View>
        </View>

        <Text style={styles.label}>Enquiries Covered</Text>
        <View style={styles.enquiryList}>
          {data.enquiries.map((e) => (
            <Text key={e.id} style={styles.value}>
              {e.ref} — {e.shipmentType ?? "—"} ({e.serviceTypes.join(", ") || "—"})
            </Text>
          ))}
        </View>

        {CATEGORY_ORDER.map((category) => {
          const items = data.lineItems.filter((li) => li.category === category);
          if (items.length === 0) return null;
          return (
            <View key={category}>
              <Text style={styles.sectionTitle}>{CATEGORY_LABEL[category]}</Text>
              {items.map((item) => (
                <View key={item.id} style={styles.row}>
                  <Text style={styles.rowDescription}>{item.description}</Text>
                  <Text style={styles.rowAmount}>
                    {item.currency} {item.amount.toFixed(2)}
                  </Text>
                </View>
              ))}
            </View>
          );
        })}

        <View style={styles.totalRow}>
          <Text>Total</Text>
          <Text>
            {data.currency} {data.totalAmount.toFixed(2)}
          </Text>
        </View>

        <Text style={styles.footer}>Generated by Seawave Forwarding &amp; Logistics — Quotation {data.ref}</Text>
      </Page>
    </Document>
  );
}
