-- AlterEnum
ALTER TYPE "QuotationStatus" ADD VALUE IF NOT EXISTS 'FLOATED';
ALTER TYPE "QuotationStatus" ADD VALUE IF NOT EXISTS 'COST_WORKING';
ALTER TYPE "QuotationStatus" ADD VALUE IF NOT EXISTS 'QUOTATION_PREPARED';
